# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for OpenDoc
# Docs: https://goreleaser.com

version: 2

project_name: opendoc

before:
  hooks:
    - go mod tidy

builds:
  - id: opendoc
    main: ./cmd/opendoc
    binary: opendoc
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

homebrew_casks:
  - repository:
      owner: cottrellashley
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/cottrellashley/bark"
    description: "A static site generator with integrated workbench and AI chat"
    binaries:
      - opendoc
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opendoc"]
          end

release:
  github:
    owner: cottrellashley
    name: bark
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto
